# Generated by Django 4.1.3 on 2022-11-17 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_toy_alter_feeding_options_hamster_toys'),
    ]

    operations = [
        migrations.AddField(
            model_name='hamster',
            name='img',
            field=models.CharField(default='', max_length=100),
        ),
    ]
