# Generated by Django 4.1.3 on 2022-11-18 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_hamster_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hamster',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='toy',
            name='img',
            field=models.CharField(default='', max_length=100),
        ),
    ]
