# Generated by Django 4.1.3 on 2022-11-18 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_hamster_options_toy_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('hamster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.hamster')),
            ],
        ),
    ]
